spring:
  application:
    name: ${SPRING_APPLICATION_NAME:order101}
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD}
server:
  port: 8080
jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.hibernate: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: DEBUG

    # kakao:
    #   client-id: ${KAKAO_CLIENT_ID}
    #   redirect-uri: ${KAKAO_REDIRECT_URI}

    # mail:
  #   host: smtp.gmail.com
  #   port: 587
  #   username:
  #   password:
  #   properties:
  #     mail:
  #       smtp:
  #         auth: true
  #         starttls:
  #           enable: true